### ISSUE TITLE
Currently reads 230.368%

### ISSUE THREAD

**Issue by GideonPARANOID** [craighep/AberDissClock#4]
Scared the living daylights out of me.

![screenshot from 2015-04-12 21 43 14](https://cloud.githubusercontent.com/assets/2547187/7107424/f7dbc5c4-e15c-11e4-9a28-d53f207bda51.png)

**Comment by craighep** [comment]
Are you bored? ;)

**Comment by GideonPARANOID** [comment]
I might be.

**Comment by craighep** [comment]
Actually, me too. I'm gonna fix it!

**Comment by craighep** [comment]
Its better now :D

**Comment by GideonPARANOID** [comment]
Awesome! But no less scary :(
